### ISSUE TITLE
bin2cpp.cpp(8,5): error C2065: 'ssize_t': undeclared identifier

### ISSUE THREAD

**Issue by zdenop** [lostjared/bin2cpp#1]
MS Visual studio does not know ssize_t. There is need to add flowing code to [bin2cpp.cpp](https://github.com/lostjared/text2cpp/blob/master/src/bin2cpp.cpp):

```c++
#if defined(_MSC_VER)
#include <BaseTsd.h>
typedef SSIZE_T ssize_t;
#endif
```

**Comment by lostjared** [comment]
Thanks, I added it.
